spring.datasource.url=jdbc:h2:file:./data/myappdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
server.port=8080
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.datasource.username=sa
spring.datasource.password=
spring.security.user.name=admin
spring.security.user.password=admin
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
management.endpoints.web.exposure.include=*
spring.security.filter.order=0